### PR TITLE
Remove support for 0.5 and drop Compat

### PR DESCRIPTION
**Pull request by iamed2**
Compat wasn't used anymore so I dropped it. If we need it again we can find a new lower version bound. 

I also bumped up the IntervalSets dependency.

### CODE REVIEW

**Comment by iamed2** [comment]
@mbauman @ajkeller34 thoughts on this?

I also have a branch where I've made some improvements using 0.6-only syntax and would love to push that as well, and get #88 in.

**Comment by ajkeller34** [comment]
Looks good to me, though over in https://github.com/JuliaArrays/AxisArrays.jl/pull/97 @timholy seemed to lean towards finishing and merging #90 before dropping 0.5 support. I'm not sure what the status of that is.

**Comment by iamed2** [comment]
I don't think anyone's around to work on that so I think at this point we could backport it to a 0.5 branch+tag if it gets in to a newer version.

**Comment by ajkeller34** [comment]
Ok, I tend to agree. I'll merge this in a few hours if I don't hear from anyone else. I'll close/reopen this PR to trigger CI again in the mean time.

**Comment by iamed2** [comment]
Thanks!

**Pull request merged**
