### PR TITLE
Basic plot support

### PR DESCRIPTION
**Pull request by jw3126**
Plot recipes for AxisArrays.
```julia
using AxisArrays
using Plots
arr1 = AxisArray(randn(10), Axis{:cost}(linspace(0,1,10)))
arr2 = AxisArray(randn(7,12), Axis{:Day}(["M", "T", "W", "T", "F", "S", "S"]), Axis{:Score}(1:12))
plot(arr1)
```
arr1
```julia
plot(arr2)
```
arr2

### CODE REVIEW

**Comment by iamed2** [comment]
I don't think there's a reason that a matrix should refer to a heat map vs multiple series or something else. 

The second graph also does not seem to display a categorical index very well.

**Comment by jw3126** [comment]
In plots there is already poor mans axis array support. And it gives you a contour plot (I misremembered it would be a heatmap). 
```julia
using Plots

data = randn(10,10)
ax2 = linspace(0,1,10)
ax1 = map(i -> "x$i", 1:10)
plt = plot(ax1, ax2, data)
```
p

So I guess thats the canonical choice.

**Comment by jw3126** [comment]
Now this behaves as follows:
```julia
using AxisArrays
using Plots
arr1 = AxisArray(randn(10), Axis{:cost}(linspace(0,1,10)))
arr2 = AxisArray(randn(7,12), Axis{:AxisName1}(["x$i" for i in 1:7]), Axis{:AxisName2}(1:12))
display(plot(arr1))
display(plot(arr2))
display(heatmap(arr2))
```
1d
2d
heatmap

**Comment by jw3126** [comment]
So what do you think of this PR:

* There is no wish to support plots inside this package?
* There is a wish to support plots here, but the PR needs changes?
* This PR is okay and can be merged?

**Comment by iamed2** [comment]
I don't know whether the maintainers would like to support plots here

**Comment by timholy** [comment]
I'm not sure either. I recognize the utility of this but am a little reluctant to "contaminate" an otherwise "pure" package. Unless someone objects I'd say we should just go ahead and merge it.

Sorry for the delay here, I am a little swamped now for reviewing anything other than stuff related to JuliaImages and Base.

**Comment by jw3126** [comment]
Sure I understand that, I will probably create a little extra package for these recipes.

**Comment by jw3126** [comment]
I moved it [here](https://github.com/jw3126/AxisArrayPlots.jl)

**Comment by timholy** [comment]
That's a fine solution too. Thanks for tackling this, and your patience.

**Comment by c42f** [comment]
I've just been wanting something like this and I think it would greatly improve the ergonomics of this package for my current use case (signal processing of magnetic resonance data). I think with the support for axis traits we can do something more useful for categorical axes as well.

I'll probably open an alternative (similar but enhanced) proposal :-)

**Pull request closed without merging**
