### PR TITLE
Add keyword indexing + constructor

### LINKED ISSUE #174: How to select a subset of an AxisArray by keyword?
I have `B = AxisArray(randn(10,10), :x, :z);`. I want to be able to do something along the lines of 
```
select(B; x = -10 .. 10)
```

or even using the syntax `B[x = -10 .. 10]`. 

1. Is this possible?
2. Would you accept it as a PR? I couldn't find something like that in the documentation.

### PR DESCRIPTION
**Pull request by mcabbott**
This adds the following behaviour:
```julia
A = AxisArray(rand(2,5), x=[:a, :b], y=11:15)
A[x=:a]
@btime A[x=:a, y=1] # 5 ns, 0 allocations
```
I think this was discussed somewhere.... only [this comment](https://github.com/JuliaArrays/AxisArrays.jl/pull/152#issuecomment-446571461) perhaps? 

Edit: this also closes #174, because you can write 
```julia
A[x=:b, y=13..14]
A[x=:b, y=atvalue(13)]
```

### CODE REVIEW

**Comment by timholy** [comment]
This seems like a nice improvement in usability. Let's give folks a couple more days to express concerns, and then I'd favor merging.

**Comment by mcabbott** [comment]
Excellent. Should I have a go at updating the readme to use this?

**Comment by timholy** [comment]
Given the lack of expressed concerns, sure, that would be great! Note that in addition to the README itself there is a `test/readme.jl` file.

**Comment by mcabbott** [comment]
OK, have added the keyword indexing lines to `test/readme.jl` too. Have not touched `docs/index.md`.

I had a go at inserting a paragraph explaining that you can now use keywords, at the top of the readme. It's not great but see what you think?

**Comment by mcabbott** [comment]
Test failure was my fault, in that https://github.com/JuliaMath/IntervalSets.jl/pull/57 causes `..` to come from EllipsisNotation.jl, and that has a method for `A[..]`. Should be fixed, except on 1.0.

**Comment by timholy** [comment]
Thanks for a lovely PR, @mcabbott!

**Pull request merged**
